services:
  server:
    container_name: server
    build: 
      context: .
      dockerfile: Dockerfile.local
    working_dir: /app
    ports:
      - 5000:5000
    restart: always
    tty: true
    volumes:
      - ./:/app